# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Batuhan Olgaç\Desktop\PipManager\pipManagerDesign.ui'
#
# Coding By = Maresal Programming | Batuhan Olgaç
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 401)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.install_Btn = QtWidgets.QPushButton(self.frame)
        self.install_Btn.setObjectName("install_Btn")
        self.verticalLayout.addWidget(self.install_Btn)
        self.update_Btn = QtWidgets.QPushButton(self.frame)
        self.update_Btn.setObjectName("update_Btn")
        self.verticalLayout.addWidget(self.update_Btn)
        self.uninstall_Btn = QtWidgets.QPushButton(self.frame)
        self.uninstall_Btn.setObjectName("uninstall_Btn")
        self.verticalLayout.addWidget(self.uninstall_Btn)
        self.surum_Btn = QtWidgets.QPushButton(self.frame)
        self.surum_Btn.setObjectName("surum_Btn")
        self.verticalLayout.addWidget(self.surum_Btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.LogoPython = QtWidgets.QLabel(self.frame)
        self.LogoPython.setMinimumSize(QtCore.QSize(60, 100))
        self.LogoPython.setMaximumSize(QtCore.QSize(90, 16777215))
        self.LogoPython.setText("")
        self.LogoPython.setObjectName("LogoPython")
        self.verticalLayout.addWidget(self.LogoPython)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PipManager | Maresal PRM"))
        self.install_Btn.setText(_translate("MainWindow", "Install"))
        self.update_Btn.setText(_translate("MainWindow", "Update"))
        self.uninstall_Btn.setText(_translate("MainWindow", "Uninstall"))
        self.surum_Btn.setText(_translate("MainWindow", "Sürüm Kontrol"))
